### ISSUE TITLE
Why Coordinated Shutdown is not used?

### ISSUE THREAD

**Issue by mralexes** [petabridge/akkadotnet-cluster-workshop#135]
Why [Coordinated Shutdown](https://getakka.net/articles/actors/coordinated-shutdown.html) is not used in this repository? This repo is the only example (at least I was not able to find more) that contains examples of Akka.NET k8s deployment

According to @Aaronontheweb answer: [here](https://stackoverflow.com/a/53290870) usage of Coordinated Shutdown
> ... is the recommended way of doing things since Akka.NET 1.3.2

**Comment by Aaronontheweb** [comment]
It is used - automatically behind the scenes. It gets called automatically because we listen to the `AppDomain.ProcessExit` event inside Akka.NET.
